### ISSUE TITLE
ROS naming guidelines and repository names

### ISSUE THREAD

**Issue by gavanderhoorn** [swri-robotics/toolpath_offline_planning#22]
(I fully realise this is going to sound like whining, but that can't be helped, so my apologies in advance)

Would it be possible to rename this repository `toolpath_offline_planning`? The current name makes it a bit hard to navigate to and sorted lists of directories also place this in a weird location, making tab-completion behave differently than with other directories.

Github should take care of redirecting everything, so you woudn't have to update anything on the client side.

Thanks :+1:

**Comment by marip8** [comment]
Agreed and changed. There is still some debate about what this repository should be named per #6, but hopefully we can come up with something soon
