### ISSUE TITLE
Failed to find match for field 

### ISSUE THREAD

**Issue by gzaidner** [swri-robotics/toolpath_offline_planning#36]
Hi,
I'm running this package for the first time.
I tried loading bunch of .ply and .stl models, also the raw mesh file from noether but I get the following error:

```
Failed to find match for field 'rgb'.
Failed to find match for field 'normal_x'.
Failed to find match for field 'normal_y'.
Failed to find match for field 'normal_z'.
Failed to find match for field 'curvature'.
```

I would be glad to have an explanation.
PCL 1.9. and vtk 7.1
Thanks

**Comment by marip8** [comment]
This is more of a warning than an error; basically PCL looks for the information in these fields in your input files but they don't exist (i.e. your mesh does not have color or normal information embedded in it). If you want this to go away, you should save your mesh with color and normal information (via PCL, Meshlab, or some other tool). Or we could change the type of point cloud this mesh is being loaded into if that information is unnecessary. What `noether` function/node are you using that generates this warning?
